language: php

php:
  - "7.4"
  - "8.0"

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - TYPO3_VERSION="^10.4"
    - TYPO3_VERSION="^11.5"

services:
  - mysql

install: composer req typo3/cms-core:$TYPO3_VERSION typo3/cms-backend:$TYPO3_VERSION typo3/cms-frontend:$TYPO3_VERSION typo3/cms-lowlevel:$TYPO3_VERSION

script:
  - .Build/bin/grumphp run
  - .Build/bin/phpunit
  - .Build/bin/phpunit -c phpunit_integration.xml
  - export TYPO3_CONTEXT=Testing
  - composer req helhum/typo3-console
  - ./.Build/bin/typo3cms configuration:set DB/Connections/Default/dbname typo3
  - ./.Build/bin/typo3cms configuration:set DB/Connections/Default/host 127.0.0.1
  - ./.Build/bin/typo3cms configuration:set DB/Connections/Default/user root
  - ./.Build/bin/typo3cms configuration:set DB/Connections/Default/password ''
  - php ./.Build/bin/typo3cms install:setup --no-interaction --force --database-user-name=root --database-user-password= --database-host-name=127.0.0.1 --database-name=typo3 --admin-user-name=admin --admin-password=password --site-setup-type=none
  - .Build/bin/phpunit -c phpunit_functional.xml