services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pluswerk\BePermissions\:
      resource: '../Classes/*'

  Pluswerk\BePermissions\Command\ExportBeGroupsCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:exoport'
        description: 'Exports a be_group to yaml file.'
  Pluswerk\BePermissions\Command\ExtendBeGroupCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:extend'
        description: 'Extends a be_group based on stored yaml file.'
  Pluswerk\BePermissions\Command\OverruleBeGroupCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:overrule'
        description: 'Overrules a be_group based on stored yaml file. Be careful with this command!'

  Pluswerk\BePermissions\UseCase\ExportBeGroupToConfigurationFile:
    public: true
  Pluswerk\BePermissions\UseCase\OverruleBeGroupFromConfigurationFile:
    public: true
  Pluswerk\BePermissions\UseCase\ExtendBeGroupByConfigurationFile:
    public: true
  Pluswerk\BePermissions\Repository\BeGroupRepository:
    public: true

