services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.api_routes:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['bepermissions_apiroutes']

  SebastianHofer\BePermissions\:
      resource: '../Classes/*'


  SebastianHofer\BePermissions\Controller\Backend\BeGroupsCompareModuleController:
    tags: ['backend.controller']

  SebastianHofer\BePermissions\Command\MergeProdBeGroupsCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:mergeprodandexport'
        description: 'Merges be_groups records from production system wth your local records and exports the result.'
  SebastianHofer\BePermissions\Command\SyncProdBeGroupsCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:syncprodbegroups'
        description: 'Synchronize be_groups from production.'
  SebastianHofer\BePermissions\Command\DeployCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:deploy'
        description: 'Extends/overrules all existing be_groups yaml configurations into database.'
  SebastianHofer\BePermissions\Command\ExportBeGroupsCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:export'
        description: 'Exports all be_groups, which are code managed to their yaml files. If an identifier is given only this be_group is exported to yaml file.'
  SebastianHofer\BePermissions\Command\ExtendBeGroupCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:extend'
        description: 'Extends a be_group based on stored yaml file.'
  SebastianHofer\BePermissions\Command\OverruleBeGroupCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:overrule'
        description: 'Overrules a be_group based on stored yaml file. Be careful with this command!'

  SebastianHofer\BePermissions\UseCase\DeployBeGroups:
    public: true
  SebastianHofer\BePermissions\UseCase\ExportBeGroupsToConfigurationFile:
    public: true
  SebastianHofer\BePermissions\UseCase\OverruleOrCreateBeGroupFromConfigurationFile:
    public: true
  SebastianHofer\BePermissions\UseCase\ExtendOrCreateBeGroupByConfigurationFile:
    public: true
  SebastianHofer\BePermissions\Repository\BeGroupRepository:
    public: true
  SebastianHofer\BePermissions\Middleware\BePermissionsApiMiddleware:
    public: true
    arguments:
      $cache: '@cache.api_routes'
  SebastianHofer\BePermissions\Api\Controller\BeGroupsController:
    public: true

