services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pluswerk\BePermissions\:
      resource: '../Classes/*'

  Pluswerk\BePermissions\Command\ExportBeGroupsCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:exoport'
        description: 'Exports a be_group to yaml file.'
  Pluswerk\BePermissions\Command\BulkExportBeGroupsCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:bulk-export'
        description: 'Exports all be_groups, which are enabled for bulk export to their yaml files.'
  Pluswerk\BePermissions\Command\ExtendBeGroupCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:extend'
        description: 'Extends a be_group based on stored yaml file.'
  Pluswerk\BePermissions\Command\OverruleBeGroupCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'bepermission:overrule'
        description: 'Overrules a be_group based on stored yaml file. Be careful with this command!'

  Pluswerk\BePermissions\UseCase\BulkExportBeGroupsToConfigurationFiles:
    public: true
  Pluswerk\BePermissions\UseCase\ExportBeGroupToConfigurationFile:
    public: true
  Pluswerk\BePermissions\UseCase\OverruleOrCreateBeGroupFromConfigurationFile:
    public: true
  Pluswerk\BePermissions\UseCase\ExtendOrCreateBeGroupByConfigurationFile:
    public: true
  Pluswerk\BePermissions\Repository\BeGroupRepository:
    public: true

