name: Run tests
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'kanti/buildy:7.4'
          - 'kanti/buildy:8.0'
        mysql: ['8.0']
    container:
      image: ${{ matrix.image }}
    services:
      mysql:

        image: mysql:5.7
        env:
          MYSQL_DATABASE: typo3
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: save-password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: composer install
      - run: ./.Build/bin/grumphp run
      - run: ./.Build/bin/phpunit
      - run: ./.Build/bin/phpunit -c phpunit_integration.xml
      - run: export TYPO3_CONTEXT=Testing
      - run: composer req helhum/typo3-console
      - run: ./.Build/bin/typo3cms install:setup --no-interaction --force --database-user-name=root --database-user-password=save-password --database-host-name=mysql --database-name=typo3 --use-existing-database --admin-user-name=admin --admin-password=password --site-setup-type=none
      - run: composer run-script link-extension
      - run: ./.Build/bin/phpunit -c phpunit_functional.xml
