name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'kanti/buildy:7.4'
          - 'kanti/buildy:8.0'
        mysql: ['8.0']
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: apk --update add tar
      - uses: docker://mysql:5.7
        with:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_RANDOM_ROOT_PASSWORD: false
      - run: composer install
      - run: ls -la
      - run: ./.Build/bin/grumphp run
      - run: ./.Build/bin/phpunit
      - run: ./.Build/bin/phpunit -c phpunit_integration.xml
      - run: export TYPO3_CONTEXT=Testing
      - run: composer req helhum/typo3-console
      - run: ./.Build/bin/typo3cms configuration:set DB/Connections/Default/dbname typo3
      - run: ./.Build/bin/typo3cms configuration:set DB/Connections/Default/host 127.0.0.1
      - run: ./.Build/bin/typo3cms configuration:set DB/Connections/Default/user root
      - run: ./.Build/bin/typo3cms configuration:set DB/Connections/Default/password root
      - run: ./.Build/bin/typo3cms install:setup --no-interaction --force --database-user-name=root --database-user-password=root --database-host-name=127.0.0.1 --database-name=typo3 --admin-user-name=admin --admin-password=password --site-setup-type=none
      - run: ./.Build/bin/phpunit -c phpunit_functional.xml
